### ISSUE TITLE
Thread safety for tracking events

### ISSUE THREAD

**Issue by DaAwesomeP** [plule/leaprs#62]
Hello!

I was able to compile and get this to compile and find `libLeapC`! I'm trying to integrate it into a multithreaded app. I intend to poll constantly in one thread and pass `Event::Tracking` to another through `mpsc::channel`. I think this is the simplest way to do it. 

However, the compiler won't let me use `Event`, `Event::Tracking`, or `Hand` types for `mpsc` as they are not thread safe. Another issue seems to be that these types somehow link back to `Connection`, so then `Connection` would need to be accessible outside of a thread.

As a workaround I could create a new intermediary type to pass between threads, but I'd like to avoid that if I can.

Or at least, I think this is what the issue is. I'm new to Rust, so please especially feel free correct me wherever necessary (though I have C/C++ experience).

Example error:
```
error[E0277]: `*mut leap_sys::_LEAP_HAND` cannot be shared between threads safely
`*mut leap_sys::_LEAP_HAND` cannot be shared between threads safely
     = help: within `TrackingEvent<'_>`, the trait `Sync` is not implemented for `*mut leap_sys::_LEAP_HAND`
note: required because it appears within the type `leap_sys::_LEAP_TRACKING_EVENT`
```

Example (uncomment the `mpsc`  lines to see `Connection` borrowing/lifetime issue):
```rust
// let (tx, _rx) = mpsc::channel();
thread::spawn(move || {
    let mut c = Connection::create(ConnectionConfig::default()).unwrap();
    c.open().unwrap();
    let poll = c.poll(1000);
    let _poll_events = match poll {
        Err(error) => panic!("Poll error: {:?}", error),
        Ok(event) => event,
    };
    loop {
        match c.poll(1000).unwrap().event() {
            LeapEvent::Tracking(e) => {
                println!("{} hand(s)", e.hands().len());
                // tx.send(e.hands()).unwrap();
            }, _ => {}
        }
    }
});
```

**Comment by DaAwesomeP** [comment]
Hey thanks for the fast response!

Ah, I see--I had assumed this data was being re-encoded/-copied into structs in Rust and passed statically without containing some common pointers/memory used internally. If the former was the case then passing the message would copy it, not reference it (at least that is my understanding).

I'll make my own structure to copy the data as you mentioned. Maybe I'll open a pull to add a handy method to do this too!

I'll close this since it was just my misunderstanding.

**Comment by plule** [comment]
> Ah, I see--I had assumed this data was being re-encoded/-copied into structs in Rust and passed statically without containing some common pointers/memory used internally. If the former was the case then passing the message would copy it, not reference it (at least that is my understanding).

Yep exactly.
