### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by plule** [plule/leaprs#70]
Leap Motion drivers now supports Mac OS.

- The library search path in `build.rs` should be updated
- General sanity checks should be done

Help wanted: I don't have a Mac.

**Comment by anselanza** [comment]
I have gotten a basic sample working on MacOS. Unfortunately it currently requires a little bit of nonsense to point to the dylib file at runtime, i.e.
```
DYLD_LIBRARY_PATH="/Applications/Ultraleap Hand Tracking.app/Contents/LeapSDK/lib" cargo run
```
